CREATE TABLE FOOD_RECIPES (
   No           INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
   Name         VARCHAR(150) NOT NULL,
   Ingredient_1 VARCHAR(200) NOT NULL,
   Ingredient_2 VARCHAR(200) NOT NULL,
   Ingredient_3 VARCHAR(200) NOT NULL,
   Ingredient_4 VARCHAR(200) NOT NULL,
   Effect       VARCHAR(300) NOT NULL
);

CREATE TABLE INGREDIENTS (
   No           INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
   Item         VARCHAR(150) NOT NULL,
   Source		VARCHAR(200) NOT NULL,
   Type			VARCHAR(150) NOT NULL,
   Note			VARCHAR(300)
);